# Generated by Django 5.0.6 on 2024-06-07 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apostador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('foto', models.ImageField(blank=True, upload_to='apostadores/')),
            ],
        ),
        migrations.CreateModel(
            name='ActualizacionApostador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ganadas', models.IntegerField(default=0)),
                ('perdidas', models.IntegerField(default=0)),
                ('fecha_actualización', models.DateTimeField(auto_now=True)),
                ('apostador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualizaciones', to='project_final.apostador')),
            ],
        ),
        migrations.CreateModel(
            name='CaracteristicaApostador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_juegos', models.IntegerField(default=0)),
                ('ganadas_del_apostador', models.IntegerField(default=0)),
                ('apostador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristica', to='project_final.apostador')),
            ],
        ),
    ]
