# Generated by Django 5.0.3 on 2024-04-25 18:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_final', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Formulario',
        ),
        migrations.RemoveField(
            model_name='apostadores',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='apostadores',
            name='detalles',
        ),
        migrations.RemoveField(
            model_name='apostadores',
            name='tu_tiempo',
        ),
        migrations.RemoveField(
            model_name='caracteristica_apostadores',
            name='juegos',
        ),
        migrations.AddField(
            model_name='apostadores',
            name='edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apostadores',
            name='fecha_inscripcion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='caracteristica_apostadores',
            name='apostador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project_final.apostadores'),
        ),
    ]
